apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  username: {{ .Values.db.username | b64enc }}
  password: {{ .Values.db.password | b64enc }}
  namespace: {{ .Release.Namespace | b64enc }}