apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongo
subjects:
- kind: ServiceAccount
  name: default