apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-pod
  template:
    metadata:
      labels:
        app: mongo-express-pod
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          requests:
            memory: 256Mi
            cpu: 0
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          value: database-0.database
        readinessProbe:
          httpGet:
            path: /
            port: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  # type: LoadBalancer
  selector:
    app: mongo-express-pod
  ports:
  - port: 8081
    targetPort: 8081