apiVersion: v1
kind: Service
metadata:
  name: {{ include "iine-grp.api.fullname" . }}
  labels:
{{ include "iine-grp.api.labels" . | indent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "iine-grp.api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
