apiVersion: v1
kind: Service
metadata:
  name: {{ include "iine-grp.web.fullname" . }}
  labels:
{{ include "iine-grp.web.labels" . | indent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "iine-grp.web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
